version: '3'

silent: true

tasks:
  all:
    desc: Performs all tasks from the building process
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: clippy
      - task: test

  build:
    desc: Builds the workspace in debug mode
    cmds:
      - cmd: cargo +stable build --workspace

  clean:
    desc: Cleans all compilation artifacts
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for the workspace and all targets
    cmds:
      - task: clippy-stable
      - task: clippy-nightly

  clippy-stable:
    desc: Runs clippy for the workspace and all targets using stable channel
    cmds:
      - cmd: cargo +stable clippy --workspace --all-targets

  clippy-nightly:
    desc: Runs clippy for the workspace and all targets using nightly channel
    cmds:
      - cmd: cargo +nightly clippy --workspace --all-targets

  cov:
    desc: Generates code coverage report for the engine
    cmds:
      - task: clean
      - cmd: ./tarpaulage.sh dtee

  cov-editor:
    desc: Generates code coverage report for the whole editor
    cmds:
      - task: clean
      - cmd: ./tarpaulage.sh dte

  doc:
    desc: Generates the documentation for the workspace
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items --workspace

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items --workspace --open

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt

  run1:
    desc: Runs the editor with example input file ./examples/e1.dtb
    cmds:
      - cmd: cargo run -- ./examples/e1.dtb

  run2:
    desc: Runs the editor with example input file ./examples/e2.dtb
    cmds:
      - cmd: cargo run -- ./examples/e2.dtb

  test:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable test --workspace

  testn:
    desc: Runs all tests in debug mode using nextest
    cmds:
      - cmd: cargo +stable nextest run --workspace
